pipeline {
    agent any
    stages {
        stage('Linux example') {
            steps {
                echo 'Hello World'
            }
        }
        // stage('Windows example') {
        //     agent {
        //         node {
        //             label 'windows10'
        //         }
        //     }
        //     steps {
        //         bat 'scrips/s1.bat'
        //     }
        // }
    }
}